<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>stint-Scheduler-E8179A4C-7A71-4C4D-A098-61C34BA1CD42</UserSecretsId>
    <PackageName>Stint.Scheduler</PackageName>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Changify" />
    <PackageReference Include="Changify.Options" />
    <PackageReference Include="Cronos" />
    <PackageReference Include="Dazinator.Extensions.DependencyInjection.NamedServices"/> 
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="MIcrosoft.Extensions.Logging.Console" />
    <!--<PackageReference Include="System.Threading.Channels" Version="5.0.0" />-->
  </ItemGroup>

</Project>
