# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pr:
  - feature/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: gitversion

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk    
    useGlobalJson: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet tool install -g dotnet-format
  displayName: Install dotnet-format
  
- script: dotnet-format -w "$(Build.SourcesDirectory)/src" -v normal --check
  displayName: Formatting Check

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.0' 

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    configuration: '$(buildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: test
    projects: '$(solution)'
    configuration: '$(buildConfiguration)'   

- task: DotNetCoreCLI@2
  inputs: 
    command: 'pack'    
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'
    
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'
